### ISSUE TITLE
No such file: ../../data/python/train/code.keyword

### ISSUE THREAD

**Issue by Li-Lixuan** [gszsectan/SG-Trans#1]
I've download the dataset from https://github.com/wasiahmad/NeuralCodeSum/tree/master/data
but there is no code.keyword or code.instatement.
please suggest where i can find the processed data.

**Comment by shuzhenggao** [comment]
Sorry for our late. 
Our processed data can be downloaded in https://drive.google.com/file/d/1c0Im6M71VHn4hv7gmnQnfqa1QtbzFjPn/view?usp=sharing.
Note that the args {train,dev,test}_ky, {train,dev,test}_t5 and {train,dev,test}_cf are not used in this work and left for future study.
You can run this model by using 

--{train,dev,test}_ky {train,dev,test}/code.${INTOKEN} \
--{train,dev,test}_t5 {train,dev,test}/code.${INTOKEN} \
--{train,dev,test}_cf {train,dev,test}/data_flow_new_subtoken.npy \

We will also refactor our code for readability in a few weeks.

**Comment by Li-Lixuan** [comment]
Thanks a lot!!
