### ISSUE TITLE
How to get the original python dataset?

### ISSUE THREAD

**Issue by yuchen-xia** [gszsectan/SG-Trans#2]
Hi! Thanks for sharing your great work!

I would like to parse the codes into asts with the dataset you used in your paper so that I can conduct some experiments, but I'm having some trouble looking for the original python dataset. It would be very helpful if you could provide the original python dataset with original split.

Thanks a lot and looking forward to your reply!

**Comment by shuzhenggao** [comment]
Hi! I update the original python dataset in SG-Trans/python/data/. The DCSP and DCNL in the files represent the tap and the line break respectively.
