### ISSUE TITLE
How do you build the data flow adjacency matrix?

### ISSUE THREAD

**Issue by bvlourenco** [gszsectan/SG-Trans#4]
Good afternoon.
I'm Bernardo Lourenço, a MSc student in Computer Science and Engineering @ Instituto Superior Técnico (Lisbon, Portugal).
I was analyzing the code of SG-Trans model and I would like to know how did you create the code.original_instatement, code.original_intoken and data_flow_new_subtoken.npy. Did you use a specific script? Can you explain it to me or send it? If you can't, that's totally fine :slightly_smiling_face: 
Thank you very much for your attention.
Kind regards,
Bernardo Lourenço

**Comment by shuzhenggao** [comment]
Thank you for your interest in our work. The data prerocess procedure can be found in section 4.1. For code.original_intoken, we apply CamelCase and snake_case tokenizers to get sub-tokens for both dataset. For code.original_instatement of Java dataset, we split each code snippet into statements with separators including ’{’, ’}’ and ’;’. ’. The token sequence between two adjacent separators is considered as a statement. While for the Python dataset, we define a statement by the row, which means that the tokens in the same row (split by ‘\n’) are considered as belonging to the same statement. For the dataflow extraction of Java dataset, we utilized the tool in GSC (https://github.com/mwcvitkovic/Open-Vocabulary-Learning-on-Source-Code-with-a-Graph-Structured-Cache--Code-Preprocessor) to generate augmented Abstract Syntax Trees (ASTs) and then removed irrelevant edges to extract Data Flow Graphs (DFGs). Regarding the Python dataset, we implement the extraction process by ourselves and extract four types of edges (LastRead, LastWrite, LastLexicalUse, ComputeFrom) from the code. If you are interested in extracting data flow information for your own code, we recommend utilizing publicly available data flow extraction tools such as the one released by GraphCodeBERT (https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch/parser)

**Comment by bvlourenco** [comment]
Thank you very much for the description and for the suggestion regarding the GraphCodeBERT data flow extraction script.

**Comment by AFunFun222** [comment]
@bvlourenco Hello. I was wondering if your response seems to indicate that you've already replicated the experiment, right? I was wondering how you converted the data set to original_instatement and original_intoken? Which piece of code is in the author's submission? Can you tell me? Please help me. Thank you.

**Comment by AFunFun222** [comment]
@shuzhenggao Hello, you said that you used CamelCase and snake_case tokenizer in code.original_intoken to get the sub-tokens, and code.origianl_instatement to get the data set with the corresponding method. However, after I opened your code.original_intoken and code.original_instatement files, I found that there are all 0 and 1 in them, which is a mask technology or vectorization technology. Besides, I did not find the method to convert the token to 0 and 1 in the code you provided. If possible, can you provide your technology on how to implement from token to 0,1 file?
