### ISSUE TITLE
Request for the files of .original_keyword, .original_intoken and .original_instatement.

### ISSUE THREAD

**Issue by AFunFun222** [gszsectan/SG-Trans#7]
Hi, I am so sorry to bother you, I was impressed by your masterpiece after reading your paper, and found this code through github just to reproduce your model results, unfortunately, You mentioned you in the dataset with Java data set is from https://github.com/wasiahmad/NeuralCodeSum/tree/master/data, But when I run it, I find that the.original_keyword,original_intoken and.original_instatement files are missing. How do you handle these files? Could you please send the document to me? My email address is afunaaa222@163.com. Thank you for reading my request. Good luck!

**Comment by bi314159** [comment]
我也没找到这几个文件，博主能发一下吗，我邮箱是1782361976@qq.com,谢谢

**Comment by AFunFun222** [comment]
https://drive.google.com/file/d/1c0Im6M71VHn4hv7gmnQnfqa1QtbzFjPn/view?usp=sharing

**Comment by AFunFun222** [comment]
Sorry, In previous issues which have closed I have find the link of "https://drive.google.com/file/d/1c0Im6M71VHn4hv7gmnQnfqa1QtbzFjPn/view?usp=sharing", and I can get the files of .original_instatement and .original_intoken in that, however, where is the files of .original_keyword?

**Comment by bvlourenco** [comment]
@AFunFun222 check this issue: https://github.com/shuzhenggao/SG-Trans/issues/1

The author says:
```
Note that the args {train,dev,test}_ky, {train,dev,test}_t5 and {train,dev,test}_cf are not used in this work and left for future study.
You can run this model by using

--{train,dev,test}_ky {train,dev,test}/code.${INTOKEN}
--{train,dev,test}_t5 {train,dev,test}/code.${INTOKEN}
--{train,dev,test}_cf {train,dev,test}/data_flow_new_subtoken.npy \
```

**Comment by AFunFun222** [comment]
@bvlourenco Oh!! Thank you very much, I am so careless that did not notice this sentence, super thanks, hope you have a good life!
